### PR TITLE
openwrt: Add Public PGP for 21.02

### PR DESCRIPTION
**Pull request by thpryrchn**
Signed-off-by: Benjamin McGuire <benjamin@reelworks.net>

This adds the PGP Public signature, so that OpenWrt 21.02 can be made.

### CODE REVIEW

**Comment by thpryrchn** [comment]
Key is from: https://git.openwrt.org/?p=keyring.git;a=blob_plain;f=gpg/88CA59E8.asc;h=e53a85b4ef5e8f46b6725a57240dac87917cbfdc;hb=bc4d80f064f2af385a78705d5de0fc8e882c3991

**Comment by stgraber** [comment]
Thanks!

Could you edit your commit message to include the required `Signed-off-by: Firstname Lastname <email>` line?

Then we can merge this fix!

**Comment by thpryrchn** [comment]
done :)

**Comment by stgraber** [comment]
Thanks!

**Pull request merged**
