### PR TITLE
test: Add Jammy support for OVN network tests

### PR DESCRIPTION
**Pull request by tomponline**
Requires https://github.com/lxc/lxd/pull/10393

Closes https://github.com/lxc/lxc-ci/issues/490

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber this can be merged, and we'll see how reliable (or not) this is on the daily tests.
It is possible to get it to complete all the way through, but the OVN version in Jammy is buggy and somtimes the ovn-controller process uses 100% CPU and the network doesn't operate. I'm struggling to identify what causes it as the logs don't contain anything different when it fails compared to a successful run. However it does appear to be related to deleting an OVN network.

**Comment by tomponline** [comment]
@stgraber suffice to say I strongly recommended sticking with Focal for your OVN hosts for now.

**Comment by stgraber** [comment]
But I'm running the jammy version of OVS and OVN and a kernel more recent than jammy so the rest of userspace being focal shouldn't matter much.

**Comment by tomponline** [comment]
> But I'm running the jammy version of OVS and OVN and a kernel more recent than jammy so the rest of userspace being focal shouldn't matter much.

Ah OK if you're running a custom version then will be interesting to see if you encounter the issues in production, or whether its just the behavior of the tests that is triggering it intermittently.

**Comment by tomponline** [comment]
@stgraber do you have a ppa I can validate with?

**Comment by tomponline** [comment]
What I do see in the logs that is different than the Focal OVN version is:

```
2022-05-11T19:21:41.270Z|00070|if_status|WARN|Dropped 2 log messages in last 50 seconds (most recently, 45 seconds ago) due to excessive rate
2022-05-11T19:21:41.270Z|00071|if_status|WARN|Trying to release unknown interface cr-lxd-net9-lr-lrp-ext
```

**Comment by stgraber** [comment]
ppa:stgraber/stgraber.net is what I run on my production servers

**Pull request merged**
