### PR TITLE
add openEuler-22.03-LTS and openEuler-20.03-LTS-SP3 image supports

### PR DESCRIPTION
**Pull request by pkking**
Signed-off-by: lichaoran <pkwarcraft@gmail.com>

### CODE REVIEW

**Comment by pkking** [comment]
@TommyLike @monstermunchkin hi, try to get openeuler image to work :)

**Comment by TommyLike** [comment]
@pkking please add the context/background for this PR

**Comment by TommyLike** [comment]
Which version(s) are added here and why @pkking

**Comment by pkking** [comment]
First of all, will try to make all LTS(openEuler-22.03-LTS and 20.03-LTS-SP3 for now) releases to work for they are most commonly used.

**Comment by TommyLike** [comment]
> openEuler-22.03-LTS and 20.03-LTS-SP3

Please update the commit message and PR header to indicate these two LTS images are supported.

**Comment by TommyLike** [comment]
@pkking thaks for your PR, it looks good to me now, waiting the maintainer to review the changes. Also I have a question regarding this new image submition.

@monstermunchkin 
1. Is there any specific image maintainer here? I mean when **this** image is unstable or have some issue/security bug report, who is responsible for handling this?
2. what's the workflow to keep this image updated.

**Review by monstermunchkin — CHANGES_REQUESTED** [review]
Looks good overall, just a few small changes on the yaml files themselves. Regarding indentation on `images/openeuler.yaml`, we don't indent list items:

```yaml
files:
- name: hostname
  path: /etc/hostname
  generator: hostname
```

Feel free to fix that as well, otherwise I can do it.

**Comment by monstermunchkin** [comment]
> Is there any specific image maintainer here? I mean when **this** image is unstable or have some issue/security bug report, who is responsible for handling this?

We maintain all our images.

> what's the workflow to keep this image updated.

We do monthly image reviews where we look for new releases and architectures, as well as releases which are EOL. Besides that we build and test our images daily. If something breaks, we fix it.

**Comment by pkking** [comment]
Ok, i will try to change distrobuilder first to make the release numbers meanningful and comparable.

**Comment by stgraber** [comment]
@monstermunchkin what's the state of this?

**Pull request merged**
