### PR TITLE
images/centos: Fix CentOS 8-Stream networking

### PR DESCRIPTION
**Pull request by monstermunchkin**

### CODE REVIEW

**Comment by stgraber** [comment]
Hmm this feels like a very nasty workaround...

@monstermunchkin what's the issue with Network Manager that makes this kind of hack necessary?

**Comment by monstermunchkin** [comment]
I don't know why NetworkManager is being weird. It behaved before. Anyway, there are two solutions (I know of) which fix the networking issue:
1. `ip link set dev eth0 up && nmcli c up "System eth0"`
2. Start the dhclient after NetworkManager

**Comment by tomponline** [comment]
@stgraber @monstermunchkin I took a quick look at this an according to:

https://bugzilla.redhat.com/show_bug.cgi?id=1832603

If you comment out the line in /usr/lib/udev/rules.d/85-nm-unmanaged.rules that mentions veth, then it works without further modification.

**Comment by tomponline** [comment]
According to that file we should be able to create an override file at `/etc/udev/rules.d`

**Comment by monstermunchkin** [comment]
Let's try this. Thanks @tomponline :)

**Comment by tomponline** [comment]
@monstermunchkin no problem. There does appear to be a separate issue, it looks like NM is preventing the container from cleanly shutting down, even with that fix (and before).

**Comment by tomponline** [comment]
@monstermunchkin oh actually it does shutdown eventually its just slow.

**Pull request merged**
