### PR TITLE
images/centos: Fix CentOS 8-Stream networking issue

### PR DESCRIPTION
**Pull request by monstermunchkin**

### CODE REVIEW

**Comment by tomponline** [comment]
@monstermunchkin The top of that file says "# Do not modify this file, it will get overwritten on updates. # To override or extend the rules place a file in /etc/udev/rules.d" so it may be prudent to add a file in /etc/udev/rules.d to override the problem rule somehow.

**Comment by tomponline** [comment]
Oh I see you've created a new file, although I wonder if using /etc/udev/rules.d would still be more appropriate. What do you think?

**Comment by monstermunchkin** [comment]
You're right. I missed that.

**Review by tomponline — APPROVED** [review]
Cool, does that override fix it ok?

**Comment by monstermunchkin** [comment]
Yes, the fix works.

**Pull request merged**
